### ISSUE TITLE
home

### ISSUE THREAD

**Issue by bharathrams** [arunjose1995/e-ulavan#4]
- [ ]in  home page  create a role pop up msg form
- 
![Screenshot from 2022-10-25 17-06-53](https://user-images.githubusercontent.com/111480975/197763976-9a74dd74-602b-4f01-94b2-a6e3f7e6b4e0.png)

- [](url)
- [ ] the to fields that was manufacturer and buyer
- [ ] click manufacturer its redirects to  manufacturer details #5 

- [ ] manufacturer details #5 
- [ ] buyer details #6 
- [ ] post products for manufacturer add their product #7 
- [ ] buying details for buyer #8 
- [ ] notification for confirmaion and to know the order for the  product #9 

- [ ]  the posted news feed show here..
- [ ] [](url)
![Screenshot from 2022-10-25 17-43-24](https://user-images.githubusercontent.com/111480975/197770512-1f5410b4-8142-4a0d-ac1a-fe0e7f1ffefe.png)

- [ ] home page looks like t
![Screenshot from 2022-10-25 18-04-44](https://user-images.githubusercontent.com/111480975/197774487-5755435a-eefd-4cd9-98c6-7a37cd578077.png)
his
- [ ] 

- [ ] example #10 
- [ ] The home page contains all the manufacturer posts and details and  notification and the   notification contains the order placed message to  the manufacturer....
